### ISSUE TITLE
issue, you havent responded to me in forever

### ISSUE THREAD

**Issue by SilverVRCode** [Spinyfish/Spinyfish#1]
solution: friend me (SilverVR) on discord (tis me, output)

**Comment by SilverVRCode** [comment]
bro did you just abandon github where are you 😭

**Comment by SilverVRCode** [comment]
@Spinyfish

**Comment by SilverVRCode** [comment]
bro i will spam this github until your email is full

**Comment by SilverVRCode** [comment]
aint no way bro doesnt care

**Comment by SilverVRCode** [comment]
nahhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh jit dont even care

**Comment by Spinyfish** [comment]
Bro I ain't use this email or acc no more I js logged in today to remove it from my old phone 😭 lemme add u when I'm home

**Comment by SilverVRCode** [comment]
WHAR HE IS ONLINE (i got the email notif fr)

**Comment by SilverVRCode** [comment]
also good friend me when u home

**Comment by Spinyfish** [comment]
Send a friend req to "rijndaelx" on discord that's my new acc

**Comment by SilverVRCode** [comment]
ok ez done
also bro i have a shit ton of stuff to catch you up on lmaooo
